# Generated by Django 3.2.18 on 2023-05-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visited',
            field=models.IntegerField(default=0),
        ),
    ]
