# Generated by Django 3.2.18 on 2023-04-28 07:39

import accounts.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230428_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=accounts.models.User.get_image_path),
        ),
    ]
